### ISSUE TITLE
Bad status line: '' when using Instagram API

### ISSUE THREAD

**Issue by citizen-stig** [gabrielfalcao/HTTPretty#182]
I'm trying to build small python application for instagram, but during unittest creation I found strange bug, that I cannot understand.

Here's example code for reproducing. It requires requests and python-instagram bindings

```
from instagram.client import InstagramAPI
import requests

import httpretty


@httpretty.activate
def get_insta_media_by_tag(tag_name):
    access_token = 'testtest'
    httpretty.register_uri(httpretty.GET, 'https://api.instagram.com/',
                           body='You did ita')
    api = InstagramAPI(access_token=access_token)
    api.tag_recent_media(tag_name=tag_name, access_token=access_token)

@httpretty.activate
def get_google_page():
    address = 'https://www.google.ru/'
    httpretty.register_uri(httpretty.GET, address,
                           body='You did it')
    response = requests.get(address)
    print response.content

#get_google_page()
get_insta_media_by_tag('#sky')
```

`get_google page()` works normally, but `get_insta_media_by_tag()` throws this exception:

```
Traceback (most recent call last):
  File "/Users/nikolaygolub/workspace/my/spasibomam/socialbots/httpretty_tests.py", line 29, in <module>
    get_insta_media_by_tag('#sky')
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/httpretty/core.py", line 1029, in wrapper
    return test(*args, **kw)
  File "/Users/nikolaygolub/workspace/my/spasibomam/socialbots/httpretty_tests.py", line 16, in get_insta_media_by_tag
    api.tag_recent_media(tag_name=tag_name, access_token=access_token)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/instagram/bind.py", line 194, in _call
    return method.execute()
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/instagram/bind.py", line 186, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/instagram/bind.py", line 119, in _do_api_request
    response, content = OAuth2Request(self.api).make_request(url, method=method, body=body, headers=headers)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/instagram/oauth2.py", line 212, in make_request
    return http_obj.request(url, method, body=body, headers=headers)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/nikolaygolub/workspace/my/tender_parser/python/lib/python2.7/site-packages/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

What can it be? I'm trying to debug this issue, maybe problem in Instagram API module, but I can't understand where. Please help.

**Comment by gabrielfalcao** [comment]
This might have been fixed by @frankamp on #216

**Comment by ianwalter** [comment]
I'm getting this error when using `xmlrpclib`. Tried installing master and still getting the error.

**Comment by gabrielfalcao** [comment]
reopenning

**Comment by porterjamesj** [comment]
possibly the same underlying issue as https://github.com/gabrielfalcao/HTTPretty/issues/65
